# Generated by Django 3.0.8 on 2020-09-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200715_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeat_by',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('F', 'Fortnightly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, verbose_name='Repeat event'),
        ),
    ]
