# Generated by Django 3.0.8 on 2020-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_repeat_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_text',
            new_name='event_name',
        ),
    ]
