# Generated by Django 3.0.8 on 2020-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_task_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Date to be completed by'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='time_for_completion',
            field=models.DurationField(null=True, verbose_name='Time needed to complete task'),
        ),
    ]
