# Generated by Django 3.0.8 on 2020-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200923_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(verbose_name='Date to be completed by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_for_completion',
            field=models.DurationField(verbose_name='Time needed to complete task'),
        ),
    ]
