# Generated by Django 3.0.8 on 2020-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200923_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_for_completion',
            field=models.DurationField(default='00 00:00:00', help_text='Format: DD HH:MM:SS', verbose_name='Time needed to complete task'),
        ),
    ]
