# Generated by Django 3.1.1 on 2020-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200924_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recommended_priority',
            field=models.IntegerField(default=0),
        ),
    ]
