# Generated by Django 3.1.1 on 2020-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200925_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_for_completion',
            field=models.DurationField(default='00:00:00', help_text='Format: HH:MM:SS', verbose_name='Time needed to complete task'),
        ),
    ]
