# Generated by Django 3.1.1 on 2020-09-26 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200925_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suggested_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 3, 34, 16, 973692, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='recommended_priority',
            field=models.IntegerField(default=99999, editable=False),
        ),
    ]
