# Generated by Django 3.1.1 on 2020-09-26 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200926_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='suggested_start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='recommended_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 3, 36, 16, 771307, tzinfo=utc), editable=False),
        ),
    ]
