# Generated by Django 3.1.3 on 2020-12-29 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200926_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recommended_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 5, 46, 41, 459545, tzinfo=utc), editable=False),
        ),
    ]
