# Generated by Django 3.1.3 on 2020-12-29 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201229_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recommended_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 22, 0, tzinfo=utc), editable=False),
        ),
    ]
