# Generated by Django 3.1.3 on 2020-12-29 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20201229_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recommended_start_time',
            field=models.DateTimeField(default=datetime.datetime(2006, 6, 13, 16, 0), editable=False),
        ),
    ]
